In [3]:
# df es la variable del data_set

import pandas as pd
df = pd.read_csv('kdrama.csv')
# df.head(1)

In [11]:
# dfk es la variable modificada "arreglada" del data_set, para su correcta visualización
# y manejo de uso

dfk = df[['Name', 'Year of release', 'N° Episode','Platform', 'Genre', 'Rank', 'Rating']]
dfk.set_index('Rank').head(5)

,Name,Year of release,N° Episode,Platform,Genre,Rating
Rank,,,,,,
#1,Move to Heaven,2021,10,Netflix,"Life, Drama, Family",9.2
#2,Hospital Playlist,2020,12,"Netflix, tvN","Friendship, Romance, Life, Medical",9.1
#3,Flower of Evil,2020,16,tvN,"Thriller, Romance, Crime, Melodrama",9.1
#4,Hospital Playlist 2,2021,12,"Netflix, tvN","Friendship, Romance, Life, Medical",9.1
#5,My Mister,2018,16,tvN,"Psychological, Life, Drama, Family",9.1

In [5]:
# "Ejemplo/Practica" de filtrado por 'Rating' (valor >= 8.8) y 'Genre'

# dfk[dfk['Genre'].str.contains('Comedy', 'Romance')]
dfk[(dfk['Rating'] >= 8.8) & dfk['Genre'].str.contains('Comedy', 'Romance')]

,Name,Year of release,N° Episode,Platform,Genre,Rank,Rating
5,Prison Playbook,2017,16,"Netflix, tvN","Comedy, Crime, Life, Drama",#6,9.1
6,Reply 1988,2015,20,tvN,"Comedy, Romance, Youth, Family",#7,9.0
7,It's Okay to Not Be Okay,2020,16,"Netflix, tvN","Psychological, Comedy, Romance, Drama",#8,9.0
8,Mr. Queen,2020,20,tvN,"Historical, Mystery, Comedy, Romance",#9,9.0
13,Vincenzo,2021,20,"Netflix, tvN","Comedy, Law, Crime, Drama",#14,9.0
14,Crash Landing on You,2019,16,"Netflix, tvN","Military, Comedy, Romance, Political",#15,9.0
20,Goblin,2016,16,tvN,"Comedy, Romance, Fantasy, Melodrama",#21,8.8
21,Hometown Cha-Cha-Cha,2021,16,"Netflix, tvN","Comedy, Romance, Life",#22,8.8
23,D.P.,2021,6,Netflix,"Action, Military, Comedy, Drama",#24,8.8
26,Weightlifting Fairy Kim Bok Joo,2016,16,MBC,"Comedy, Romance, Youth, Sports",#27,8.8
28,Life on Mars,2018,16,OCN,"Action, Mystery, Comedy, Supernatural",#29,8.8
34,Racket Boys,2021,16,"Netflix, SBS","Friendship, Comedy, Youth, Sports",#35,8.8